[package]
name = "rust-cli"
description = "Super simple Rust Clap example"
version = "0.1.3"
authors = ["Chris <electronicsleep@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
