[package]
name = "rust-cli"
description = "Rust cli"
version = "0.1.1"
authors = ["Chris <electronicsleep@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
